### ISSUE TITLE
SkullTextureTransformer is missing

### ISSUE THREAD

**Issue by mcmdev** [cerus/easy-item#1]
This class is required in ParserBuilder but isn't present in the transformer package

**Comment by cerus** [comment]
Thank you for bringing that to my attention, the SkullTextureTransformer is currently broken and thus not present in the repository. I have removed the references to that class in 1.1.0.
Please let me know if that solves the issue

**Comment by cerus** [comment]
No further response from OP, I assume the issue has been resolved. Please re-open if that's not the case, thank you!
